### ISSUE TITLE
Winpmem help needed

### ISSUE THREAD

**Issue by sarathkumar21** [Velocidex/WinPmem#29]
Hi All,

I'm trying to send the ram dump output to the remote host directly, instead of touching to the disk using socat.

It's getting failed.

Client( wIndows)
.\winpmem_mini_x64_rc2.exe -w |  .\socat.exe -t 100 -T 100 TCP:**IP**:443 STDIN
 
 Please do the needful.

**Comment by scudette** [comment]
[image: Windows.png]

So this should work

.\winpmem_mini_x64_rc2.exe - | .\socat.exe -t 100 -T 100 TCP:*IP*:443 STDIN

Thanks
Mike

Mike Cohen
Digital Paleontologist,
Velocidex Enterprises
M  ‭+61 470 238 491‬  <‭+61+470+238+491‬>
E ***@***.***  ***@***.***>

**Comment by sarathkumar21** [comment]
Hi @scudette 

Thanks, What changes we need to make in linux server, just wanted to write the file?  socat -u TCP-LISTEN:443 STDOUT

**Comment by sarathkumar21** [comment]
@scudette Thanks issue has been fixed.
