### ISSUE TITLE
memmap performance 

### ISSUE THREAD

**Issue by kevthehermit** [Velocidex/WinPmem#39]
### Issue

When comparing the performance of `memdump` in volatility 2 and `memmap` in volatility 3 I have noticed a significant performance impact.

First discussed on Slack - https://volatilitycommunity.slack.com/archives/CNV2K4V9Q/p1639950485064800 , opening a GIt issue with more details. 

### Expected Behaviour

`memdump` and `memmap --dump` processing times should be comparable. 

### Actual Behaviour
Running the command with Vol2 takes ~8 seconds to dump and Vol3 takes almost 3 minutes. 

### Host Details

Host OS: Ubuntu 20.04
Image: AWS Server 2016 `Win2016x64_14393`
Collection: `winpmem_mini_x64_rc2.exe`

### Volatility 2.6

```
time vol.py -f image1.raw --profile Win2016x64_14393 memdump -p 4604 -D . 
Volatility Foundation Volatility Framework 2.6
************************************************************************
Writing rundll32.exe [  4604] to 4604.dmp

real	0m8.385s
user	0m7.564s
sys	0m0.807s
```

### Volatility 3 (develop Branch)

```
vol -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604 --dump  
... Lots of print to screen all the offsets. 

174.19s user 3.10s system 99% cpu 2:57.57 total
```

###  write-config

Using `--write-config` and then running again with the resulting config file has no significant change in the time 

```
vol -c config.json -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604
161.77s user 2.52s system 99% cpu 2:44.76
```

### Other Plugins

Other plugins run in a "normal" amount of time

- `vol -f image1.raw --output-dir=procdump/ windows.pslist  1.40s user 0.44s syst
em 99% cpu 1.841 total`

### Profile

Performance profile captured with the following command 

```
python3 -m cProfile -o out.prof vol.py -f image1.raw --output-dir=procdump/ windows.memmap --pid 4604 --dump
```

[profile.zip](https://github.com/Velocidex/WinPmem/files/7741730/profile.zip)

**Comment by scudette** [comment]
I think you might want to file this on the volatility GitHub. This is for winpmem itself.

**Comment by kevthehermit** [comment]
Sorry,
