### ISSUE TITLE
WinPmem startup time increases proportional to system on time

### ISSUE THREAD

**Issue by Blightbuster** [Velocidex/WinPmem#59]
Coming here from https://github.com/ufrisk/MemProcFS/issues/333

**Comment by scudette** [comment]
Its not really clear to me what does "initialization" mean in this context? loading the driver? enumerating the physical memory ranges?

We know that on some configurations (MS calls it dynamic memory) the number of physical memory ranges increases all the time - we have seen thousands even. This is not really a winpmem issue but an MS windows memory fragmentation issue. Can you confirm the correct number of physical ranges ? It is in the registry here
HKEY_LOCAL_MACHINE\HARDWARE\RESOURCEMAP\System Resources\Physical Memory\.Translated

See this for an artifact that can parse that
https://docs.velociraptor.app/artifact_references/pages/windows.sys.physicalmemoryranges/

**Comment by vivianezw** [comment]
Winpmem does not have a startup time. Having thousands of physical ranges doesn't disturb Winpmem - it simply refuses working immediately when there is an abnormal amount. That's a drastic way to deal with it, but also very final.

I'd say same as Scudette. If it's Hyper-V based, try turning off dynamic memory to prevent physical ranges from exploding over time. But if it's not Hyper-V backbone, it would be another issue.

**Comment by Blightbuster** [comment]
Unfortunately I dont know either what exactly takes that long is there perhaps a way to enable some debugging logs?
This is a screenshot of my physical memory ranges, seems like they are alright? It took 4 minutes to get vmm (which loads winpmem) started when I took that one.

![image](https://github.com/user-attachments/assets/9a752626-0294-43c2-81c0-64f5cf1cf266)

**Comment by scudette** [comment]
Those look fine - are you sure the time is spend in loading the driver? I am not familiar with VMM but maybe there is some debugging there to enable while it is waiting to load the driver?

You can also install https://learn.microsoft.com/en-us/sysinternals/downloads/debugview and enable kernel debugging to see log messages from the driver. Loading the driver itself should take no time - we dont actually wait for anything ourselves.

Also work checking are the system and application event logs for messages around starting the service

**Comment by Blightbuster** [comment]
Closing as it does seem to be related to memprocfs afterall and is probably caused by the large count of running/terminated processes being enumerated. Sorry for any troubles.
